### ISSUE TITLE
can't see the video

### ISSUE THREAD

**Issue by markzhong88** [rupeshs/neuralstyler#1]
Saw your website and try the code on my ubuntu, it shows video created, but after I click open styledvideo folder, I can't see anything there. Please advise. 

Here is the console output:

---

Style Frame ok
Style start
Style Frame ok
Style start
Style Frame ok
creating styled video
Styled video created

(nautilus:3053): GLib-GIO-CRITICAL **: g_dbus_interface_skeleton_unexport: assertion 'interface_->priv->connections != NULL' failed

(nautilus:3053): GLib-GIO-CRITICAL **: g_dbus_interface_skeleton_unexport: assertion 'interface_->priv->connections != NULL' failed

(nautilus:3053): Gtk-CRITICAL **: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

(nautilus:3053): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(nautilus:3053): GLib-GObject-CRITICAL **: g_signal_connect_object: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

**Comment by rupeshs** [comment]
You need ffmpeg and chainer virtualenv.Download neuralstyler for Ubuntu from neuralstyler.com ,extract it you will get ffmpeg and env folder copy env and styles folder to the debug/release folder env folder contains chainer virtualenv.
