### ISSUE TITLE
v2.0 crash

### ISSUE THREAD

**Issue by Fuj-** [rupeshs/neuralstyler#2]
Hello,

Just tested NeuralStyler v2.0 and it crashes on startup. I get a window titled "Microsoft Visual C++ Runtime Library" which throws the following error "This application has requested the Runtime to terminate it in an unusual way. Please contact the application's support team for more information".
NeuralStyler v1.0 works fine.

System: Win7 SP1 x64
VC++ redist installed:
2005 V8.0.61000
2008 V9.0.30729
2010 V10.0.40219
2012 V11.0.61030
2013 V12.0.30501
2015 V14.0.24406

**Comment by rupeshs** [comment]
Please download NeuralStyler 2.0.1 https://sourceforge.net/projects/neuralstyler/files/Windows/neuralstyler-2.0.1-portable-x64.7z/download

**Comment by Fuj-** [comment]
v2.0.1 is working without problems.

**Comment by rupeshs** [comment]
Closing this issue
